<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250918100414 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE document_document_tags (document_id VARCHAR(36) NOT NULL, document_tag_id VARCHAR(36) NOT NULL, PRIMARY KEY (document_id, document_tag_id))');
        $this->addSql('CREATE INDEX IDX_EFA7BC3EC33F7837 ON document_document_tags (document_id)');
        $this->addSql('CREATE INDEX IDX_EFA7BC3E4B0D277 ON document_document_tags (document_tag_id)');
        $this->addSql('CREATE TABLE user_group_users (user_group_id VARCHAR(36) NOT NULL, user_id VARCHAR(36) NOT NULL, PRIMARY KEY (user_group_id, user_id))');
        $this->addSql('CREATE INDEX IDX_EDB4471B1ED93D47 ON user_group_users (user_group_id)');
        $this->addSql('CREATE INDEX IDX_EDB4471BA76ED395 ON user_group_users (user_id)');
        $this->addSql('ALTER TABLE document_document_tags ADD CONSTRAINT FK_EFA7BC3EC33F7837 FOREIGN KEY (document_id) REFERENCES documents (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_document_tags ADD CONSTRAINT FK_EFA7BC3E4B0D277 FOREIGN KEY (document_tag_id) REFERENCES document_tags (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_group_users ADD CONSTRAINT FK_EDB4471B1ED93D47 FOREIGN KEY (user_group_id) REFERENCES user_groups (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_group_users ADD CONSTRAINT FK_EDB4471BA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_document_tag DROP CONSTRAINT fk_document_document_tag_document_id');
        $this->addSql('ALTER TABLE document_document_tag DROP CONSTRAINT fk_document_document_tag_document_tag_id');
        $this->addSql('ALTER TABLE user_user_group DROP CONSTRAINT fk_user_user_group_user_id');
        $this->addSql('ALTER TABLE user_user_group DROP CONSTRAINT fk_user_user_group_user_group_id');
        $this->addSql('DROP TABLE document_document_tag');
        $this->addSql('DROP TABLE user_user_group');
        $this->addSql('ALTER TABLE audit_logs DROP CONSTRAINT fk_audit_logs_user_id');
        $this->addSql('ALTER TABLE audit_logs DROP CONSTRAINT fk_audit_logs_document_id');
        $this->addSql('ALTER TABLE audit_logs ADD resource VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE audit_logs ADD resource_id VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE audit_logs ADD level VARCHAR(20) DEFAULT \'info\' NOT NULL');
        $this->addSql('ALTER TABLE audit_logs ALTER action TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE audit_logs ALTER metadata DROP DEFAULT');
        $this->addSql('ALTER TABLE audit_logs ALTER metadata DROP NOT NULL');
        $this->addSql('COMMENT ON COLUMN audit_logs.created_at IS \'\'');
        $this->addSql('ALTER TABLE audit_logs ADD CONSTRAINT FK_D62F2858A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE audit_logs ADD CONSTRAINT FK_D62F2858C33F7837 FOREIGN KEY (document_id) REFERENCES documents (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX idx_auditlog_resource ON audit_logs (resource)');
        $this->addSql('CREATE INDEX idx_auditlog_level ON audit_logs (level)');
        $this->addSql('ALTER INDEX idx_audit_logs_document_id RENAME TO IDX_D62F2858C33F7837');
        $this->addSql('ALTER INDEX idx_audit_logs_action RENAME TO idx_auditlog_action');
        $this->addSql('ALTER INDEX idx_audit_logs_created_at RENAME TO idx_auditlog_created');
        $this->addSql('ALTER INDEX idx_audit_logs_user_id RENAME TO idx_auditlog_user');
        $this->addSql('ALTER TABLE categories DROP CONSTRAINT fk_categories_parent_id');
        $this->addSql('ALTER TABLE categories ADD is_active BOOLEAN DEFAULT true NOT NULL');
        $this->addSql('ALTER TABLE categories ADD sort_order INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE categories ALTER name TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE categories ALTER slug TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE categories ALTER color DROP DEFAULT');
        $this->addSql('ALTER TABLE categories ALTER color DROP NOT NULL');
        $this->addSql('ALTER TABLE categories ALTER icon TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE categories ALTER icon DROP DEFAULT');
        $this->addSql('ALTER TABLE categories ALTER icon DROP NOT NULL');
        $this->addSql('ALTER TABLE categories ALTER created_at DROP NOT NULL');
        $this->addSql('ALTER TABLE categories ALTER updated_at DROP NOT NULL');
        $this->addSql('COMMENT ON COLUMN categories.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN categories.updated_at IS \'\'');
        $this->addSql('ALTER TABLE categories ADD CONSTRAINT FK_3AF34668727ACA70 FOREIGN KEY (parent_id) REFERENCES categories (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER INDEX uniq_categories_slug RENAME TO UNIQ_3AF34668989D9B62');
        $this->addSql('ALTER INDEX idx_categories_parent_id RENAME TO IDX_3AF34668727ACA70');
        $this->addSql('DROP INDEX uniq_document_tags_name');
        $this->addSql('ALTER TABLE document_tags ADD description TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE document_tags ADD icon VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE document_tags ADD is_active BOOLEAN DEFAULT true NOT NULL');
        $this->addSql('ALTER TABLE document_tags ADD is_system BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE document_tags ADD sort_order INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE document_tags ADD created_by_id VARCHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE document_tags ALTER name TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE document_tags ALTER slug TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE document_tags ALTER color DROP DEFAULT');
        $this->addSql('ALTER TABLE document_tags ALTER color DROP NOT NULL');
        $this->addSql('ALTER TABLE document_tags ALTER created_at DROP NOT NULL');
        $this->addSql('ALTER TABLE document_tags ALTER updated_at DROP NOT NULL');
        $this->addSql('COMMENT ON COLUMN document_tags.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN document_tags.updated_at IS \'\'');
        $this->addSql('ALTER TABLE document_tags ADD CONSTRAINT FK_C80818B5B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_C80818B5B03A8386 ON document_tags (created_by_id)');
        $this->addSql('CREATE INDEX idx_tag_name ON document_tags (name)');
        $this->addSql('CREATE INDEX idx_tag_slug ON document_tags (slug)');
        $this->addSql('CREATE INDEX idx_tag_usage ON document_tags (usage_count)');
        $this->addSql('ALTER INDEX uniq_document_tags_slug RENAME TO UNIQ_C80818B5989D9B62');
        $this->addSql('ALTER TABLE documents DROP CONSTRAINT fk_documents_category_id');
        $this->addSql('ALTER TABLE documents DROP CONSTRAINT fk_documents_owner_id');
        $this->addSql('DROP INDEX idx_documents_checksum');
        $this->addSql('DROP INDEX idx_documents_owner_id');
        $this->addSql('ALTER TABLE documents ADD original_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE documents ADD metadata JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE documents ADD processing_status VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE documents ADD processing_error TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE documents ADD thumbnail_path VARCHAR(500) DEFAULT NULL');
        $this->addSql('ALTER TABLE documents ADD version_number INT NOT NULL');
        $this->addSql('ALTER TABLE documents ADD archived BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE documents ADD extracted_date DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE documents ADD extracted_amount NUMERIC(15, 2) DEFAULT NULL');
        $this->addSql('ALTER TABLE documents ADD searchable_content TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE documents ADD language VARCHAR(5) NOT NULL');
        $this->addSql('ALTER TABLE documents ADD confidence_score NUMERIC(3, 2) DEFAULT NULL');
        $this->addSql('ALTER TABLE documents DROP owner_id');
        $this->addSql('ALTER TABLE documents DROP title');
        $this->addSql('ALTER TABLE documents DROP checksum');
        $this->addSql('ALTER TABLE documents DROP ocr_confidence');
        $this->addSql('ALTER TABLE documents DROP processed_at');
        $this->addSql('ALTER TABLE documents DROP version');
        $this->addSql('ALTER TABLE documents ALTER file_path TYPE TEXT');
        $this->addSql('ALTER TABLE documents ALTER updated_at DROP NOT NULL');
        $this->addSql('COMMENT ON COLUMN documents.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN documents.updated_at IS \'\'');
        $this->addSql('ALTER TABLE documents ADD CONSTRAINT FK_A2B0728812469DE2 FOREIGN KEY (category_id) REFERENCES categories (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_documents_category_id RENAME TO IDX_A2B0728812469DE2');
        $this->addSql('DROP INDEX uniq_user_groups_name');
        $this->addSql('ALTER TABLE user_groups ADD slug VARCHAR(100) NOT NULL');
        $this->addSql('ALTER TABLE user_groups ADD is_active BOOLEAN DEFAULT true NOT NULL');
        $this->addSql('ALTER TABLE user_groups ADD is_system BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE user_groups ADD created_by_id VARCHAR(36) DEFAULT NULL');
        $this->addSql('ALTER TABLE user_groups ALTER permissions DROP DEFAULT');
        $this->addSql('ALTER TABLE user_groups ALTER created_at DROP NOT NULL');
        $this->addSql('ALTER TABLE user_groups ALTER updated_at DROP NOT NULL');
        $this->addSql('COMMENT ON COLUMN user_groups.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN user_groups.updated_at IS \'\'');
        $this->addSql('ALTER TABLE user_groups ADD CONSTRAINT FK_953F224DB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_953F224D989D9B62 ON user_groups (slug)');
        $this->addSql('CREATE INDEX IDX_953F224DB03A8386 ON user_groups (created_by_id)');
        $this->addSql('CREATE INDEX idx_usergroup_name ON user_groups (name)');
        $this->addSql('CREATE INDEX idx_usergroup_slug ON user_groups (slug)');
        $this->addSql('ALTER TABLE users ALTER preferences DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER preferences DROP NOT NULL');
        $this->addSql('ALTER TABLE users ALTER created_at DROP NOT NULL');
        $this->addSql('ALTER TABLE users ALTER updated_at DROP NOT NULL');
        $this->addSql('COMMENT ON COLUMN users.last_login_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN users.email_verified_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN users.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN users.updated_at IS \'\'');
        $this->addSql('ALTER INDEX uniq_users_email RENAME TO UNIQ_1483A5E9E7927C74');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE document_document_tag (document_id VARCHAR(36) NOT NULL, document_tag_id VARCHAR(36) NOT NULL, PRIMARY KEY (document_id, document_tag_id))');
        $this->addSql('CREATE INDEX idx_document_document_tag_document_tag_id ON document_document_tag (document_tag_id)');
        $this->addSql('CREATE INDEX idx_document_document_tag_document_id ON document_document_tag (document_id)');
        $this->addSql('CREATE TABLE user_user_group (user_id VARCHAR(36) NOT NULL, user_group_id VARCHAR(36) NOT NULL, PRIMARY KEY (user_id, user_group_id))');
        $this->addSql('CREATE INDEX idx_user_user_group_user_group_id ON user_user_group (user_group_id)');
        $this->addSql('CREATE INDEX idx_user_user_group_user_id ON user_user_group (user_id)');
        $this->addSql('ALTER TABLE document_document_tag ADD CONSTRAINT fk_document_document_tag_document_id FOREIGN KEY (document_id) REFERENCES documents (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE document_document_tag ADD CONSTRAINT fk_document_document_tag_document_tag_id FOREIGN KEY (document_tag_id) REFERENCES document_tags (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_user_group ADD CONSTRAINT fk_user_user_group_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_user_group ADD CONSTRAINT fk_user_user_group_user_group_id FOREIGN KEY (user_group_id) REFERENCES user_groups (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE document_document_tags DROP CONSTRAINT FK_EFA7BC3EC33F7837');
        $this->addSql('ALTER TABLE document_document_tags DROP CONSTRAINT FK_EFA7BC3E4B0D277');
        $this->addSql('ALTER TABLE user_group_users DROP CONSTRAINT FK_EDB4471B1ED93D47');
        $this->addSql('ALTER TABLE user_group_users DROP CONSTRAINT FK_EDB4471BA76ED395');
        $this->addSql('DROP TABLE document_document_tags');
        $this->addSql('DROP TABLE user_group_users');
        $this->addSql('ALTER TABLE audit_logs DROP CONSTRAINT FK_D62F2858A76ED395');
        $this->addSql('ALTER TABLE audit_logs DROP CONSTRAINT FK_D62F2858C33F7837');
        $this->addSql('DROP INDEX idx_auditlog_resource');
        $this->addSql('DROP INDEX idx_auditlog_level');
        $this->addSql('ALTER TABLE audit_logs DROP resource');
        $this->addSql('ALTER TABLE audit_logs DROP resource_id');
        $this->addSql('ALTER TABLE audit_logs DROP level');
        $this->addSql('ALTER TABLE audit_logs ALTER action TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE audit_logs ALTER metadata SET DEFAULT \'{}\'');
        $this->addSql('ALTER TABLE audit_logs ALTER metadata SET NOT NULL');
        $this->addSql('COMMENT ON COLUMN audit_logs.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE audit_logs ADD CONSTRAINT fk_audit_logs_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE audit_logs ADD CONSTRAINT fk_audit_logs_document_id FOREIGN KEY (document_id) REFERENCES documents (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_auditlog_user RENAME TO idx_audit_logs_user_id');
        $this->addSql('ALTER INDEX idx_d62f2858c33f7837 RENAME TO idx_audit_logs_document_id');
        $this->addSql('ALTER INDEX idx_auditlog_action RENAME TO idx_audit_logs_action');
        $this->addSql('ALTER INDEX idx_auditlog_created RENAME TO idx_audit_logs_created_at');
        $this->addSql('ALTER TABLE categories DROP CONSTRAINT FK_3AF34668727ACA70');
        $this->addSql('ALTER TABLE categories DROP is_active');
        $this->addSql('ALTER TABLE categories DROP sort_order');
        $this->addSql('ALTER TABLE categories ALTER name TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE categories ALTER slug TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE categories ALTER color SET DEFAULT \'#3B82F6\'');
        $this->addSql('ALTER TABLE categories ALTER color SET NOT NULL');
        $this->addSql('ALTER TABLE categories ALTER icon TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE categories ALTER icon SET DEFAULT \'folder\'');
        $this->addSql('ALTER TABLE categories ALTER icon SET NOT NULL');
        $this->addSql('ALTER TABLE categories ALTER created_at SET NOT NULL');
        $this->addSql('ALTER TABLE categories ALTER updated_at SET NOT NULL');
        $this->addSql('COMMENT ON COLUMN categories.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN categories.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE categories ADD CONSTRAINT fk_categories_parent_id FOREIGN KEY (parent_id) REFERENCES categories (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX uniq_3af34668989d9b62 RENAME TO uniq_categories_slug');
        $this->addSql('ALTER INDEX idx_3af34668727aca70 RENAME TO idx_categories_parent_id');
        $this->addSql('ALTER TABLE document_tags DROP CONSTRAINT FK_C80818B5B03A8386');
        $this->addSql('DROP INDEX IDX_C80818B5B03A8386');
        $this->addSql('DROP INDEX idx_tag_name');
        $this->addSql('DROP INDEX idx_tag_slug');
        $this->addSql('DROP INDEX idx_tag_usage');
        $this->addSql('ALTER TABLE document_tags DROP description');
        $this->addSql('ALTER TABLE document_tags DROP icon');
        $this->addSql('ALTER TABLE document_tags DROP is_active');
        $this->addSql('ALTER TABLE document_tags DROP is_system');
        $this->addSql('ALTER TABLE document_tags DROP sort_order');
        $this->addSql('ALTER TABLE document_tags DROP created_by_id');
        $this->addSql('ALTER TABLE document_tags ALTER name TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE document_tags ALTER slug TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE document_tags ALTER color SET DEFAULT \'#6B7280\'');
        $this->addSql('ALTER TABLE document_tags ALTER color SET NOT NULL');
        $this->addSql('ALTER TABLE document_tags ALTER created_at SET NOT NULL');
        $this->addSql('ALTER TABLE document_tags ALTER updated_at SET NOT NULL');
        $this->addSql('COMMENT ON COLUMN document_tags.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN document_tags.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE UNIQUE INDEX uniq_document_tags_name ON document_tags (name)');
        $this->addSql('ALTER INDEX uniq_c80818b5989d9b62 RENAME TO uniq_document_tags_slug');
        $this->addSql('ALTER TABLE documents DROP CONSTRAINT FK_A2B0728812469DE2');
        $this->addSql('ALTER TABLE documents ADD owner_id VARCHAR(36) NOT NULL');
        $this->addSql('ALTER TABLE documents ADD title VARCHAR(500) NOT NULL');
        $this->addSql('ALTER TABLE documents ADD checksum VARCHAR(64) NOT NULL');
        $this->addSql('ALTER TABLE documents ADD ocr_confidence DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE documents ADD processed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE documents ADD version INT DEFAULT 1 NOT NULL');
        $this->addSql('ALTER TABLE documents DROP original_name');
        $this->addSql('ALTER TABLE documents DROP metadata');
        $this->addSql('ALTER TABLE documents DROP processing_status');
        $this->addSql('ALTER TABLE documents DROP processing_error');
        $this->addSql('ALTER TABLE documents DROP thumbnail_path');
        $this->addSql('ALTER TABLE documents DROP version_number');
        $this->addSql('ALTER TABLE documents DROP archived');
        $this->addSql('ALTER TABLE documents DROP extracted_date');
        $this->addSql('ALTER TABLE documents DROP extracted_amount');
        $this->addSql('ALTER TABLE documents DROP searchable_content');
        $this->addSql('ALTER TABLE documents DROP language');
        $this->addSql('ALTER TABLE documents DROP confidence_score');
        $this->addSql('ALTER TABLE documents ALTER file_path TYPE VARCHAR(1000)');
        $this->addSql('ALTER TABLE documents ALTER updated_at SET NOT NULL');
        $this->addSql('COMMENT ON COLUMN documents.processed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN documents.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN documents.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE documents ADD CONSTRAINT fk_documents_category_id FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE documents ADD CONSTRAINT fk_documents_owner_id FOREIGN KEY (owner_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_documents_checksum ON documents (checksum)');
        $this->addSql('CREATE INDEX idx_documents_owner_id ON documents (owner_id)');
        $this->addSql('ALTER INDEX idx_a2b0728812469de2 RENAME TO idx_documents_category_id');
        $this->addSql('ALTER TABLE user_groups DROP CONSTRAINT FK_953F224DB03A8386');
        $this->addSql('DROP INDEX UNIQ_953F224D989D9B62');
        $this->addSql('DROP INDEX IDX_953F224DB03A8386');
        $this->addSql('DROP INDEX idx_usergroup_name');
        $this->addSql('DROP INDEX idx_usergroup_slug');
        $this->addSql('ALTER TABLE user_groups DROP slug');
        $this->addSql('ALTER TABLE user_groups DROP is_active');
        $this->addSql('ALTER TABLE user_groups DROP is_system');
        $this->addSql('ALTER TABLE user_groups DROP created_by_id');
        $this->addSql('ALTER TABLE user_groups ALTER permissions SET DEFAULT \'[]\'');
        $this->addSql('ALTER TABLE user_groups ALTER created_at SET NOT NULL');
        $this->addSql('ALTER TABLE user_groups ALTER updated_at SET NOT NULL');
        $this->addSql('COMMENT ON COLUMN user_groups.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN user_groups.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_groups_name ON user_groups (name)');
        $this->addSql('ALTER TABLE users ALTER created_at SET NOT NULL');
        $this->addSql('ALTER TABLE users ALTER updated_at SET NOT NULL');
        $this->addSql('ALTER TABLE users ALTER preferences SET DEFAULT \'{}\'');
        $this->addSql('ALTER TABLE users ALTER preferences SET NOT NULL');
        $this->addSql('COMMENT ON COLUMN users.last_login_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN users.email_verified_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN users.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN users.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX uniq_1483a5e9e7927c74 RENAME TO uniq_users_email');
    }
}
